
services:
  wakacje-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wakacje
    restart: always
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
