// prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function ensureTablesExist() {
    // For SQLite: look into sqlite_master. For other DBs you could adapt this check.
    const required = ["columns", "offers", "offer_values"];
    for (const tbl of required) {
        // Using a raw query against sqlite_master
        const res: any = await prisma.$queryRaw`SELECT name FROM sqlite_master WHERE type='table' AND name = ${tbl}`;
        if (!res || (Array.isArray(res) && res.length === 0)) {
            return { ok: false, missing: tbl };
        }
    }
    return { ok: true };
}

async function main() {
    console.log("Start seeding...");

    const check = await ensureTablesExist();
    if (!check.ok) {
        console.error(
            `Database table "${check.missing}" is missing. Run migrations or prisma db push before seeding.\n` +
            `Commands:\n  npx prisma migrate dev --name init\n  OR\n  npx prisma db push\nThen run the seed again: npx prisma db seed  (or npx ts-node prisma/seed.ts)`
        );
        process.exit(1);
    }

    // Upsert columns (id is generated by Prisma, but we use unique fieldId)
    const columns = [
        { fieldId: "kategoria", label: "Kategoria", icon: "Building", order: 1 },
        { fieldId: "lokalizacja", label: "Lokalizacja", icon: "MapPin", order: 2 },
        { fieldId: "kategoria_hotelu", label: "Kategoria hotelu", icon: "Building", order: 3 },
        { fieldId: "ocena", label: "Ocena", icon: "Star", order: 4 },
        { fieldId: "typ_wyzywienia", label: "Typ wyżywienia", icon: "Utensils", order: 5 },
        { fieldId: "za_osobe_dziennie", label: "za osobę (dziennie)", icon: "Users", order: 6 },
        { fieldId: "udogodnienia", label: "Udogodnienia w obiekcie", icon: "Wifi", order: 7 },
        { fieldId: "atrakcje_w_poblizu", label: "Atrakcje w pobliżu", icon: "Navigation", order: 8 },
        { fieldId: "pokoje_przykladowe", label: "Pokoje (przykładowe)", icon: "Bed", order: 9 },
        { fieldId: "dodatkowe_koszty", label: "Dodatkowe koszty", icon: "DollarSign", order: 10 },
        { fieldId: "dodatkowo_za_wszystkich", label: "Dodatkowo za wszystkich", icon: "DollarSign", order: 11 },
        { fieldId: "zalety", label: "Zalety", icon: "CheckCircle", order: 12 },
        { fieldId: "wady", label: "Wady", icon: "XCircle", order: 13 },
        { fieldId: "link_do_oferty", label: "Link do oferty", icon: "ExternalLink", order: 14 },
        { fieldId: "cena_za_nocleg", label: "Cena za nocleg", icon: "DollarSign", order: 15 },
        { fieldId: "w_sumie_za_wszystkich", label: "W sumie za wszystkich", icon: "DollarSign", order: 16 },
        { fieldId: "w_sumie_za_osobe", label: "W sumie za osobę", icon: "DollarSign", order: 17 },
        { fieldId: "flight_wylot", label: "Lot (wylot)", icon: "Plane", order: 18 },
        { fieldId: "flight_powrot", label: "Lot (powrót)", icon: "Plane", order: 19 }
    ];

    for (const col of columns) {
        await prisma.column.upsert({
            where: { fieldId: col.fieldId },
            update: { label: col.label, icon: col.icon, order: col.order },
            create: col
        });
    }

    // Remove any existing offers (so seed is deterministic)
    await prisma.offerValue.deleteMany({});
    await prisma.offer.deleteMany({});

    // Offer data
    const hotelMelitonValues = [
        { fieldId: "kategoria", value: "Hotel Meliton" },
        {
            fieldId: "lokalizacja",
            value:
                `Theologos (wieś) – 1,3 km od plaży
1,5 km od centrum Theologos
20 km od miasta Rodos
15 min samochodem od lotniska (Rhodes International Airport)`
        },
        { fieldId: "kategoria_hotelu", value: "3-gwiazdkowy, 71 pokoi" },
        { fieldId: "ocena", value: "★ 4,2 – Bardzo dobry (≈ 698 opinii)" },
        {
            fieldId: "typ_wyzywienia",
            value:
                `All-Inclusive – śniadanie, obiad, kolacja (bufet)
Przekąski i napoje 10:30-22:30`
        },
        { fieldId: "za_osobe_dziennie", value: "0" },
        {
            fieldId: "udogodnienia",
            value:
                `Darmowe Wi-Fi w całym hotelu
Basen odkryty ze słodką wodą
Jacuzzi (SPA)
Kort tenisowy
Tenis stołowy
Minipiłka nożna
Animacje (wieczory taneczne, karaoke, minigolf)
Bar główny (drinki od 16:00, koktajle od 21:00)
Wypożyczalnia rowerów/skuterów (partner Hi-Way)
Wypożyczalnia samochodów (od 40 €/dzień)`
        },
        {
            fieldId: "atrakcje_w_poblizu",
            value:
                `Dolina Motyli (9 km) – transport 10 €, wstęp 6 €
Farma zwierząt (ok. 10 km)
Centrum Theologos (sklepy, bary)
Rodos – miasto historyczne (autobus 40 min, bilet 3 €)`
        },
        {
            fieldId: "pokoje_przykladowe",
            value:
                `Pokój 2-osobowy (DZX1): 22 m²; 2 osoby; ok. 5 266 zł/7 dni (All-Inclusive)
Wyposażenie: TV sat., sejf (płatny), lodówka, suszarka, biurko, Wi-Fi, balkon/taras
Klimatyzacja – płatna

Pokój 2-osobowy superior (DZX2): 25 m²; 2 osoby; ok. 3 871 zł/7 dni (All-Inclusive)
Klimatyzacja w cenie (maj-paź)`
        },
        {
            fieldId: "dodatkowe_koszty",
            value:
                `Klimatyzacja w standardowych pokojach – 10 € / doba
Ręczniki basenowe, parasole, leżaki – ok. 10 € / zestaw
Podatek klimatyczny – 5 € / pokój / noc
Transfer lotnisko-hotel – dodatkowo płatny`
        },
        {
            fieldId: "dodatkowo_za_wszystkich",
            value: JSON.stringify({ total: 894.6, currency: "PLN", note: "dodatkowe koszty za wszystkich" })
        },
        {
            fieldId: "zalety",
            value:
                `Czyste pokoje
Dwa baseny
Spokojna okolica, dobra baza wypadowa
Dobre połączenia komunikacyjne
Darmowe Wi-Fi
Liczne atrakcje hotelowe`
        },
        {
            fieldId: "wady",
            value:
                `Monotonne jedzenie, ograniczony wybór napojów
Drinki dopiero od 16:00
Płatne niektóre udogodnienia (klimatyzacja, ręczniki, leżaki)
Plaża kamienista, 1,3 km od hotelu
Nieprzyjazna obsługa przy wydawaniu alkoholu`
        },
        { fieldId: "link_do_oferty", value: "TUI – Hotel Meliton" },
        { fieldId: "cena_za_nocleg", value: JSON.stringify({ total: 14444.0, currency: "PLN" }) },
        { fieldId: "w_sumie_za_wszystkich", value: JSON.stringify({ total: 15338.6, currency: "PLN" }) },
        { fieldId: "w_sumie_za_osobe", value: JSON.stringify({ total: 3067.72, currency: "PLN" }) },
        { fieldId: "flight_wylot", value: "" },
        { fieldId: "flight_powrot", value: "" }
    ];

    const bayviewValues = [
        { fieldId: "kategoria", value: "Bayview Village" },
        {
            fieldId: "lokalizacja",
            value:
                `Korfos, Peloponnisos Dytiki Ellada ke Ionio, Grecja
(łącznie: Teatr Epidaurus 55 km, Starożytny Korynt 40 km, Nafplio 60 km, Mycenae 55 km)`
        },
        { fieldId: "kategoria_hotelu", value: "Luksusowe wille" },
        { fieldId: "ocena", value: "★ 4,29/5 (56 recenzji)" },
        { fieldId: "typ_wyzywienia", value: "Self-catering (samodzielne przygotowywanie posiłków)" },
        { fieldId: "za_osobe_dziennie", value: "200" },
        {
            fieldId: "udogodnienia",
            value:
                `Basen (70 m²)
Darmowe Wi‑Fi
Klimatyzacja
Kominek
Pełna kuchnia
Telewizor 50''
Darmowy parking`
        },
        {
            fieldId: "atrakcje_w_poblizu",
            value:
                `Plaża przy willi
Restauracje i bary z lokalnymi daniami i rybami
Piekarnie z codziennym chlebem
Supermarkety
Teatr Epidaurus (55 km)
Starożytny Korynt (40 km)
Nafplio (60 km)
Mycenae (55 km)`
        },
        {
            fieldId: "pokoje_przykladowe",
            value:
                `Willa dla 5 osób
2 sypialnie (1 z podwójnym łóżkiem, 1 z dwoma pojedynczymi)
1,5 łazienki
Weranda z widokiem na morze
Weranda z widokiem na góry
Salon na piętrze`
        },
        {
            fieldId: "dodatkowe_koszty",
            value:
                `Bilety samolotowe - /4768zł
Transfer lotnisko-hotel - /ok. 600zł`
        },
        { fieldId: "dodatkowo_za_wszystkich", value: JSON.stringify({ total: 5368.0, currency: "PLN", note: "loty + transfer" }) },
        {
            fieldId: "zalety",
            value:
                `Duża przestrzeń
Prywatny basen
Widoki na morze i góry
Bliskość plaży
Komfortowe wyposażenie`
        },
        {
            fieldId: "wady",
            value:
                `Brak restauracji i baru na terenie obiektu
Konieczność samodzielnego przygotowywania posiłków`
        },
        { fieldId: "link_do_oferty", value: "airbnb\nskyscanner" },
        { fieldId: "cena_za_nocleg", value: JSON.stringify({ total: 3338.0, currency: "PLN" }) },
        { fieldId: "w_sumie_za_wszystkich", value: JSON.stringify({ total: 15706.0, currency: "PLN" }) },
        { fieldId: "w_sumie_za_osobe", value: JSON.stringify({ total: 3141.2, currency: "PLN" }) },
        { fieldId: "flight_wylot", value: "" },
        { fieldId: "flight_powrot", value: "" }
    ];

    // Create offers
    const offer1 = await prisma.offer.create({
        data: {
            values: {
                create: hotelMelitonValues
            }
        },
        include: { values: true }
    });

    const offer2 = await prisma.offer.create({
        data: {
            values: {
                create: bayviewValues
            }
        },
        include: { values: true }
    });

    console.log(`Created offers: ${offer1.id} and ${offer2.id}`);
    console.log("Seeding finished.");
}

main()
    .catch((e) => {
        console.error("Seed error:", e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });